apiVersion: cd.tmax.io/v1
kind: Application
metadata:
  name: application-sample
spec:
  source:
    repoURL: "https://github.com/tmax-cloud/cd-example-apps"
    path: "guestbook/guestbook-ui-svc.yaml"
    targetRevision: "main"
  destination:
    namespace: default
