apiVersion: v1
kind: Service
metadata:
  name: cd-webhook
  namespace: cd-system
  labels:
    cd.tmax.io/part-of: controller
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: webhook
    port: 24335
  - name: api
    port: 34335
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cd-webhook
  namespace: cd-system
  labels:
    cd.tmax.io/part-of: controller
spec:
  rules:
    - host: waiting.for.loadbalancer
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cd-webhook
                port:
                  number: 24335
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cd-config
  namespace: cd-system
  labels:
    cd.tmax.io/part-of: controller
data:
  externalHostName: ""
  ingressClass: ""
  ingressHost: ""
